export const QUESTIONS_LIST = {
    GET: 'GET_QUESTIONS',
    SUCCESS: 'SUCCESS_QUESTIONS',
    FAIL: 'FAIL_QUESTIONS',
    CLEAR: 'CLEAR_QUESTIONS',
}

export const QUESTION_DETAILS = {
    GET: 'GET_QUESTION_DETAIL',
    SUCCESS: 'SUCCESS_QUESTION_DETAIL',
    FAIL: 'FAIL_QUESTION_DETAIL',
    CLEAR: 'CLEAR_QUESTION_DETAIL',
}

export const POST_VOTE = {
    POST: 'POST_POST_VOTE',
    SUCCESS: 'SUCCESS_POST_VOTE',
    FAIL: 'FAIL_POST_VOTE',
}

export const POST_QUESTION = {
    POST: 'POST_POST_QUESTION',
    SUCCESS: 'SUCCESS_POST_QUESTION',
    FAIL: 'FAIL_POST_QUESTION',
}

