export const USER_DETAILS = {
    GET: 'GET_USER_DETAILS',
    SUCCESS: 'SUCCESS_USER_DETAILS',
    FAIL: 'FAIL_USER_DETAILS',
    CLEAR: 'CLEAR_USER_DETAILS',
}

export const REPO_DETAILS = {
    GET: 'GET_REPO_DETAILS',
    SUCCESS: 'SUCCESS_REPO_DETAILS',
    FAIL: 'FAIL_REPO_DETAILS',
    CLEAR: 'CLEAR_REPO_DETAILS',
}

